### ISSUE TITLE
Character is twisted

### ISSUE THREAD

**Issue by TheDevster** [kibook/redm-ball#1]
When I first push  /ball <type>, the character twists to where the front is facing backwards.. This becomes fixed when I right click (aim) and while I hold aim the character looks fine.  Shows the arm go back as if gearing up to throw; but as soon as I let go of the aim button, the character twists again (front top half of body contorts to face backwards)

**Comment by kibook** [comment]
What ped model are you using? mp_male/mp_female? I'm not able to replicate this unfortunately. Here's how it looks for me: https://streamable.com/x43q79. I've tried a few different models but they all seem to work.

If you can, try it on a "clean" server without any other resources besides the default ones, to rule out another resource interfering with it somehow.

**Comment by TheDevster** [comment]
Thanks.. I'll test it out on a fresh server.
